Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuestBook.Models;
using GuestBook.Repository;

namespace GuestBook.Controllers
{
    public class MessagesController : Controller
    {
        IRepository<Messages> _repository;
        IRepository<Users> _repo;
        public MessagesController(IRepository<Messages> context, IRepository<Users> repo)
        {
            _repository = context;
            _repo = repo;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetList());
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messages = await _repository.GetObject(id);
            if (messages == null)
            {
                return NotFound();
            }

            return View(messages);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Message")] Messages messages)
        {
            if (ModelState.IsValid)
            {
                messages.CreatedDate = DateTime.Now;
                messages.Id_user =Convert.ToInt32(HttpContext.Session.GetString("UserID"));
                messages.Owner =await _repo.GetObject(messages.Id_user);
                await _repository.Create(messages);
                await _repository.Save();
                return View(nameof(Index),await _repository.GetList());
            }
            return View("~/View/Account/Create.cshtml",messages);
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messages = await _repository.GetObject(id);
            if (messages == null)
            {
                return NotFound();
            }
            return View(messages);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Message")] Messages messages)
        {
            if (id != messages.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    messages.CreatedDate = DateTime.Now;
                    messages.Id_user = Convert.ToInt32(HttpContext.Session.GetString("UserID"));
                    messages.Owner = await _repo.GetObject(messages.Id_user);
                    _repository.Update(messages);
                    await _repository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessagesExists(messages.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), messages);
            }
            return View(messages);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messages = await _repository.GetObject(id);
            if (messages == null)
            {
                return NotFound();
            }

            return View(messages);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            
            if (id != null)
            {
                _repository.Delete(id);
            }

            await _repository.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool MessagesExists(int id)
        {
            if(_repository.GetObject(id).Result!=null)
            return true;
            return false;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuestBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GuestBook.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container-fluid" style="display: flex; justify-content: space-between">
                <a class="navbar-brand" asp-area="" asp-controller="Messages" asp-action="Index" style="width: 60%">GuestBook - Главная</a>
                @if (Context.Session.GetString("FirstName") == null)
                {
                    <div style="display: flex;width: 20%">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>

                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                    </div>
                }
                else
                {
                    <span class="navbar-brand"> @Context.Session.GetString("FirstName")  @Context.Session.GetString("LastName")</span>
                    <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Выйти</a>
                }
                
               
                      
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GuestBook @* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>